spring.application.name=UPI-Lite-Engine


# Docker Local Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/upidb
spring.datasource.username=bablu
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Virtual Threads (Java 21 Feature)
spring.threads.virtual.enabled=true